version: '3.8'

services:
  network-intelligence-api:
    build: .
    container_name: network-intelligence-sandbox
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=info
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.network-api.rule=PathPrefix(`/api/v1`)"
      - "traefik.http.services.network-api.loadbalancer.server.port=8000"
    networks:
      - sandbox-network

networks:
  sandbox-network:
    driver: bridge